'use client';

import { useState } from 'react';

const repo = 'https://github.com/kevinforge/orbit';
const tabs = [
  { id: 'route', number: '01', title: '明确路由', detail: '把工作交给对的人' },
  { id: 'trace', number: '02', title: '看见过程', detail: '每一步都有迹可循' },
  { id: 'recover', number: '03', title: '随时接管', detail: '暂停、审批、继续' }
];

function Brand() {
  return <a className="brand" href="#top" aria-label="Orbit 首页"><span className="brand-mark" aria-hidden="true"><i /></span><span>Orbit</span></a>;
}

function WorkspaceMock() {
  return <div className="hero-product" aria-label="Orbit 工作区界面示意">
    <div className="product-window">
      <div className="window-bar"><div className="window-controls" aria-hidden="true"><span /><span /><span /></div><span className="window-title">orbit / launch-plan</span><span className="window-status"><i /> 3 employees online</span></div>
      <div className="workspace-shell">
        <aside className="workspace-nav" aria-label="工作区示意导航"><div className="nav-avatar">O</div><div className="nav-line active"><span className="nav-glyph">◌</span> Overview</div><div className="nav-line"><span className="nav-glyph">↗</span> Conversations</div><div className="nav-line"><span className="nav-glyph">⌘</span> Employees</div><div className="nav-spacer" /><div className="nav-line muted"><span className="nav-glyph">⚙</span> Settings</div></aside>
        <div className="workspace-main"><div className="workspace-heading"><div><span className="tiny-label">CONVERSATION / 04</span><h2>Launch plan</h2></div><span className="live-badge">RUNNING</span></div><div className="workspace-thread"><div className="thread-message human"><div className="message-label"><span className="person-dot">Y</span> You <time>10:42</time></div><p>把这次发布拆成一份可执行的计划，并标出风险。</p></div><div className="thread-message agent"><div className="message-label"><span className="agent-dot">A</span> Aria <span className="role">PRODUCT</span><time>10:43</time></div><p>我会先梳理范围与验收标准，再交给工程和测试并行推进。</p></div><div className="thread-message agent compact"><div className="message-label"><span className="agent-dot green">C</span> Cai <span className="role">ENGINEERING</span><span className="queued">IN QUEUE</span></div><div className="progress-line"><span /><b>正在准备实现方案</b><small>02:14</small></div></div></div><div className="workspace-composer"><span>Message the team...</span><b>↗</b></div></div>
        <aside className="workspace-activity"><span className="tiny-label">ACTIVITY</span><div className="activity-item"><i className="done" /><span>Scope defined<small>just now</small></span></div><div className="activity-item"><i className="live" /><span>Aria is working<small>product review</small></span></div><div className="activity-item"><i /><span>Cai is queued<small>engineering</small></span></div><div className="activity-rule" /><div className="activity-note"><b>Local session</b><span>Every message is yours to keep.</span></div></aside>
      </div>
    </div>
    <div className="product-caption"><span className="caption-mark">↳</span> One conversation, many hands.</div>
  </div>;
}

function WorkflowPanel({ tab }: { tab: string }) {
  if (tab === 'trace') return <div className="trace-view"><div className="route-top"><span className="tiny-label">SESSION LOG</span><span className="route-count">replayable</span></div><div className="trace-row"><span className="trace-time">10:42</span><i className="trace-line-dot done" /><div><b>Goal received</b><small>You asked the team to prepare a release plan.</small></div></div><div className="trace-row"><span className="trace-time">10:43</span><i className="trace-line-dot live" /><div><b>Work routed</b><small>Aria, Cai and Tian picked up their roles.</small></div></div><div className="trace-row"><span className="trace-time">10:45</span><i className="trace-line-dot" /><div><b>Waiting for results</b><small>Nothing disappears while the work is in motion.</small></div></div></div>;
  if (tab === 'recover') return <div className="recover-view"><span className="pause-icon">Ⅱ</span><div><span className="tiny-label">CONTROL WHEN IT MATTERS</span><h3>Your work, your call.</h3><p>需要确认时再确认，需要暂停时就暂停。Orbit 会把可恢复的状态留在本地，而不是让一次中断变成一次重来。</p><a href={`${repo}/blob/main/docs/ARCHITECTURE.md`}>阅读架构原则 <span>↗</span></a></div></div>;
  return <div className="route-view"><div className="route-top"><span className="tiny-label">ASSIGNMENT MAP</span><span className="route-count">3 routes / 1 goal</span></div><div className="route-goal"><span className="route-icon">◎</span><div><b>Prepare v1.2 release</b><small>One shared outcome</small></div></div><div className="route-branch"><div className="route-node"><span className="agent-dot">A</span><div><b>Aria</b><small>Scope &amp; acceptance</small></div><strong>DONE</strong></div><div className="route-node"><span className="agent-dot green">C</span><div><b>Cai</b><small>Implementation</small></div><strong className="in-progress">WORKING</strong></div><div className="route-node"><span className="agent-dot purple">T</span><div><b>Tian</b><small>Regression check</small></div><strong className="waiting">QUEUED</strong></div></div></div>;
}

export default function Home() {
  const [tab, setTab] = useState('route');
  const [copied, setCopied] = useState(false);
  const copyInstall = async () => {
    try { await navigator.clipboard.writeText('npm install -g @kevinforge/orbit\norbit'); setCopied(true); window.setTimeout(() => setCopied(false), 1600); } catch { setCopied(false); }
  };
  return <><header className="topbar"><div className="container topbar-inner"><Brand /><nav className="topnav" aria-label="主导航"><a href="#why">为什么 Orbit</a><a href="#workflow">工作方式</a><a href={repo}>GitHub ↗</a></nav><a className="topbar-cta" href="#quickstart">开始使用 <span>↗</span></a></div></header><main id="main"><span id="top" />
    <section className="hero" aria-labelledby="hero-title"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot" /> LOCAL-FIRST · OPEN SOURCE</div><h1 id="hero-title">让 Agent<br /><em>真正成为你的团队。</em></h1><p className="hero-lede">Orbit 把 Claude Code、Codex 与 CodeBuddy 编排进一个本地优先的工作区。你负责方向，数字员工负责把事情做完。</p><div className="hero-actions"><a className="button button-dark" href={repo}>查看源码 <span>↗</span></a><a className="button button-light" href="#quickstart">三分钟开始 <span>↓</span></a></div><div className="hero-meta"><span><strong>01</strong> 一个工作区</span><span><strong>02</strong> 多个专家</span><span><strong>03</strong> 清晰可回看</span></div></div><WorkspaceMock /></div></section>
    <section className="statement" id="why"><div className="container statement-grid"><div className="section-index">01 / THE IDEA</div><div><h2>工具越来越多，<br /><span>上下文不该越来越碎。</span></h2><p className="statement-lede">Orbit 不是又一个聊天窗口。它是一个把目标、分工、审批和结果放在一起的控制面，让 Agent 的能力变成一支真正可调度的团队。</p></div></div></section>
    <section className="principles section-pad"><div className="container"><div className="section-heading-row"><div><div className="section-index">02 / BUILT FOR REAL WORK</div><h2>少一点魔法，<br /><span>多一点掌控。</span></h2></div><p>Orbit 把复杂性放在该放的位置：运行时留在适配器，状态留在本地，会话留在你手里。</p></div><div className="principle-grid"><article className="principle-card card-dark"><span className="card-number">01</span><div className="card-symbol">↗</div><h3>一个目标，多位专家</h3><p>在同一条会话里，让产品、架构、开发和测试按你的节奏接力。</p><a href="#workflow">看它怎么协作 <span>→</span></a></article><article className="principle-card card-paper"><span className="card-number">02</span><div className="card-symbol">◷</div><h3>过程清楚，结果可信</h3><p>每一步都可见、可暂停、可恢复。你知道谁在做什么，也知道下一步是什么。</p><a href="#workflow">了解可回看工作流 <span>→</span></a></article><article className="principle-card card-lime"><span className="card-number">03</span><div className="card-symbol">⌂</div><h3>本地优先，数据归你</h3><p>工作区、消息、会话与附件保存在本机。你的工作不需要绕远路。</p><a href={`${repo}/blob/main/docs/DATA_DIRECTORY.md`}>查看数据目录 <span>↗</span></a></article></div></div></section>
    <section className="workflow section-pad" id="workflow"><div className="container"><div className="section-index">03 / THE WORKFLOW</div><div className="workflow-heading"><h2>把协作过程，<br /><em>留在视线里。</em></h2><p>不是把任务丢给黑盒，而是让每一段工作都有位置、有负责人、有回声。</p></div><div className="workflow-layout"><div className="workflow-tabs" role="tablist" aria-label="Orbit 工作方式">{tabs.map((item) => <button key={item.id} role="tab" className={`workflow-tab${tab === item.id ? ' is-active' : ''}`} aria-selected={tab === item.id} onClick={() => setTab(item.id)}><span>{item.number}</span><b>{item.title}</b><small>{item.detail}</small></button>)}</div><div className="workflow-panels"><div className="workflow-panel" role="tabpanel"><WorkflowPanel tab={tab} /></div></div></div></div></section>
    <section className="demo section-pad"><div className="container"><div className="demo-intro"><div><div className="section-index">04 / SEE IT IN MOTION</div><h2>从一句话，<br /><em>到一支队伍。</em></h2></div><p>一次真实的复杂协作运行：拆解、并行、核验，最后在同一个会话里收敛。</p></div><figure className="demo-media"><div className="demo-frame"><img src="/assets/orbit-complex-collaboration-demo.gif" alt="Orbit 复杂协作演示：监工拆解任务、并行执行、核验与汇总。" /></div><figcaption><span>Orbit / complex collaboration</span><span>真实工作流演示 ↗</span></figcaption></figure></div></section>
    <section className="quickstart section-pad" id="quickstart"><div className="container quickstart-shell"><div className="section-index">05 / GET STARTED</div><div className="quickstart-heading"><h2>把 Orbit 放进<br /><em>你的工作区。</em></h2><p>需要 Node.js 22 或更高版本，以及至少一个已登录的运行时。</p></div><div className="install-box"><div className="install-copy"><span className="tiny-label">QUICK INSTALL</span><h3>从命令行开始。</h3><p>安装完成后，运行 <code>orbit</code>，然后在浏览器打开本地工作区。</p><a href={`${repo}/blob/main/docs/QUICKSTART.zh-CN.md`}>阅读中文快速上手 ↗</a></div><div className="command"><div className="command-top"><span>TERMINAL</span><button type="button" className={`copy-btn${copied ? ' is-copied' : ''}`} onClick={copyInstall}>{copied ? '已复制' : '复制'}</button></div><code><span>$</span> npm install -g @kevinforge/orbit<br /><span>$</span> orbit</code><small>localhost:4317</small></div></div></div></section>
    <section className="final-cta"><div className="container final-cta-inner"><div className="section-index">ORBIT / 2026</div><h2>下一件事，<br /><em>让团队来做。</em></h2><p>开源 · 本地优先 · 由你调度</p><div className="hero-actions"><a className="button button-lime" href={repo}>在 GitHub 上开始 <span>↗</span></a><a className="button button-outline" href={`${repo}/issues`}>告诉我们你的想法 <span>↗</span></a></div></div></section>
  </main><footer className="footer"><div className="container footer-inner"><Brand /><nav aria-label="页脚导航"><a href={`${repo}/blob/main/docs/ARCHITECTURE.md`}>架构</a><a href={`${repo}/blob/main/docs/DATA_DIRECTORY.md`}>数据</a><a href={`${repo}/blob/main/CONTRIBUTING.md`}>贡献</a><a href={`${repo}/blob/main/SECURITY.md`}>安全</a></nav><span className="footer-note">MIT License · Made for focused work.</span></div></footer></>;
}
